### PR TITLE
Parse the output of uname to determine the architecture

### PR DESCRIPTION
**Pull request by vasilmkd**
Add support for arm64 GitHub Actions runners.

Related to #29.

### CODE REVIEW

**Review by olafurpg — APPROVED** [review]
LGTM 👍 Thank you!

**Comment by olafurpg** [comment]
This fix should be released in v11!

**Comment by vasilmkd** [comment]
I just remembered, I was on a flight. Maybe we should `trim` the output string?

**Comment by olafurpg** [comment]
@vasilmkd Go ahead! I'm happy to merge another PR and cut a new release :)

**Pull request merged**
