### PR TITLE
Setup Coursier and sbtn

### PR DESCRIPTION
**Pull request by adpi2**
## Setup Coursier

Coursier can be useful to install any kind of Scala tool inside a Github job.

## Setup sbtn

As a shorter alternative to `sbt --client`, as described in #36.

### CODE REVIEW

**Comment by laughedelic** [comment]
@adpi2 have you seen https://github.com/laughedelic/coursier-setup? it basically does the same thing: install coursier and use it to install sbtn or any other coursier-installable apps or optionally install JVM.

**Comment by adpi2** [comment]
@laughedelic Thanks for pointing this out to me! It does indeed the same thing. Yet I think cs and sbtn are valuable additions to this setup for the repos that are already using it.

**Comment by olafurpg** [comment]
Thank you for this contribution! I agree this would be nice functionality to have but I'm not sure if I want to extend the scope of this repo. I think a better home for this functionality would be a repo under the official Scala GitHub organization.

This repo was created before GitHub Actions provided `sbt` in the base image and before Coursier added support to install JVMs (which explains why it uses jabba instead of coursier). The most important part for me is to reduce the risk of introducing breaking changes for existing users.

**Comment by olafurpg** [comment]
Closing this as "won't fix" because I think this feature is outside the scope of the project. @adpi2 I encourage you to push for having an official setup-scala action that's maintained by the Scala GitHub organization.

**Comment by adpi2** [comment]
Yes, we discussed this opportunity today at the Scala Center team meeting and we are going to explore it in different ways.

**Comment by olafurpg** [comment]
@adpi2 I am also happy to transfer ownership of this repo to the Scala Center if there is interest. I don't intend to archive this repo, it's just feature complete from my perspective. I can totally understand that other people want more functionality.

**Pull request closed without merging**
