### PR TITLE
provide official sbt launch script as default

### PR DESCRIPTION
**Pull request by SethTisue**
also continue providing sbt-extras, but as `sbtx`

Olaf has already indicated (on Discord, I think it was?) that this change would be welcome

### CODE REVIEW

**Comment by SethTisue** [comment]
I haven't tested this, but the change seems pretty straightforward.

**Comment by SethTisue** [comment]
fyi @dwijnand @eed3si9n

**Review by olafurpg — APPROVED** [review]
LGTM thank you! I’ll cut a new release later today.

**Comment by olafurpg** [comment]
v13 is out https://github.com/olafurpg/setup-scala/releases/tag/v13

**Comment by sideeffffect** [comment]
Hello guys, may I ask what is the motivation for this change? :slightly_smiling_face:

**Comment by olafurpg** [comment]
@sideeffffect I think this PR fixes the issues here https://github.com/olafurpg/setup-scala/issues/35

**Comment by SethTisue** [comment]
@sideeffffect see https://github.com/sbt/sbt/issues/2889, where I have just left some fresh commentary (since this is bigger than just setup-scala)

**Comment by SethTisue** [comment]
I just noticed at https://github.com/olafurpg/setup-scala/releases/tag/v13 that it says:

> csbt and sbtx launcher scripts will be removed in the next release. The official sbt script will be the only supported script going forward

that surprises me a bit, actually. I personally don't mind, but perhaps someone else will want to make an argument for retaining the alternates?

**Comment by olafurpg** [comment]
@SethTisue I’m not using those scripts and I don’t think other people are using them either. It would be nice to avoid installing those scripts.

**Pull request merged**
